package com.ds.implementation.stack.linkedList

fun main() {
    val stack = Stack<Int>()
    stack.push(1)
    stack.push(2)
    stack.push(3)
    stack.push(4)
    stack.print("Print top should 4")
    println("Pop -> ${stack.pop()}")
    stack.print("After pop 4")
    stack.push(4)
    stack.push(5)
    stack.push(6)
    stack.push(7)
    stack.push(8)
    stack.push(9)
    stack.push(10)
    stack.print("After push 4 to 10")
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.print("Pop 9 entries")
    println("${stack.pop()}")
    stack.print("Pop last entry 1")
}