package com.ds.implementation.stack.array

fun main() {
    val stack = Stack<Int>(10)
    stack.push(1)
    stack.push(2)
    stack.push(3)
    stack.push(4)
    stack.print()
    println("Pop -> ${stack.pop()}")
    stack.print("After pop 4")
    stack.push(4)
    stack.push(5)
    stack.push(6)
    stack.push(7)
    stack.push(8)
    stack.push(9)
    stack.push(10)
    stack.print("After push 4 to 10")
    println("Adding 11 ${stack.push(11)}")
    stack.print("After failing to add 11")
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    stack.pop()
    println("1 -> ${stack.pop()}")
    stack.print("Pop 9 entries")
    stack.print("Pop top 1")
    println("${stack.pop()}")
    stack.print("Print after Pop")
}